<?php $helper = new Model\Helper()?>


<!DOCTYPE html>
<html>
   <head>
      <title>login</title>
      <script src="https://kit.fontawesome.com/a076d05399.js"></script>
      <link rel="stylesheet" type="text/css" href="public/css/style.css">
   </head>
   <style type="text/css">
   </style>
   <body>
      <div class="body">
         <header class="flex">
            <div class="navbar1 ">
               <div>
                  <a><i class="fa fa-bell favi-con" aria-hidden="true"/></i></a>
                  <a href="/mvcphp/login"> Home</a>
                  <a href="/mvcphp/signup">sign-up</a>
               </div>
            </div>
         </header>
         <div  class="flexcontainer">
            <div class="block">
               <img class="img" src="public/images/1.jpg">
               <div class="block1">
                  <form action="<?=$helper->buildUrl()?>/submit/login" method="POST">
                     <table class="table">
                        <tr>
                           <th>
                              <input class="input" type="email" name="email" value="a@a.com" placeholder="enter your email" required/>
                           </th>
                        </tr>
                        <tr>
                           <th>
                              <input class="input" type="password" name="password" value="a" placeholder="enter your password" required />
                           </th>
                        </tr>
                        <tr>
                           <th>
                              <input class="button" type="submit" name="submit" value="submit" required>
                           </th>
                        </tr>
                     </table>
                  </form>
               </div>
            </div>
         </div>
         <footer class="footer">
            <div class="navbar ">
               <a href="#Settings">Settings</a>
               <a href="#Privacy">Privacy</a>
               <a href="#terms">Terms</a>
               <div  class="navba">
                  <a href="#Advertising">Advertising</a>
                  <a href="#Business">Business</a>
                  <a href="#about">About</a>
               </div>
            </div>
         </footer>
      </div>
   </body>
</html>